DARPA-ASKEM/orchestration

.github/CODEOWNERS
.github/workflows/bake-publish.yml
.github/workflows/lint-docker.yml
.github/workflows/lint-yaml.yml
.github/workflows/publish.yaml

Minor cleanup and adding threshold for docker failures. Reduces the owners for this repo for now.

ci: cleanup

---

kubernetes/local/hmi-server-deployment.yaml

moved oidc secret to container env variable

chore: moved oidc secret to env variable

---

kubernetes/local/gateway-keycloak-realm.yaml

Added the postman callback url so that devs can test APIs with postman

fix: added postman callback for testing APIs

---

README.md
kubernetes/local/deploy-terarium.sh
kubernetes/local/model-service-deployment.yaml
kubernetes/local/model-service-service.yaml

adding model-service to kubernetes cluster on port 3010
Resolves #35 

feat: 35 task add model service to orchestration scripts

---

kubernetes/local/hmi-server-deployment.yaml

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

chore: updated deploy scripts for hmi-server

---

.github/pull_request_template.md

chore: update pr message

---

.github/pull_request_template.md
kubernetes/local/data-service-graphdb-deployment.yaml
kubernetes/local/gateway-postgres-deployment.yaml

Change local kubernetes deployment files to includes our organisation packages.

chore: update which packages to pull

---

kubernetes/overlays/dev/local/services/data-service-graphdb-deployment.yaml
kubernetes/overlays/dev/local/services/kustomization.yaml
kubernetes/overlays/prod/base/services/data-service-graphdb-deployment.yaml
kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml
kubernetes/overlays/prod/overlays/askem-staging/kustomization.yaml

Ensure that neo4j uses a custom image that allows parameterization of a postgres connection

fix: neo4j cannot connect to postgres

---

kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml

Upgrade production from `0.3.6` to `0.3.7` for Data Service

chore: data-service up version

---

kubernetes/dev_deploy.sh
kubernetes/overlays/dev/local/kustomization.yaml

fix: fixed dev deployment scripts

---

kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml

chore: update production for 1 hackathon evaluation 2

---

.github/workflows/integration-issues.yml

This allows any issues to be tagged with integration label. Once tagged the issue will be added to this project issues table https://github.com/orgs/DARPA-ASKEM/projects/5/

feat: add Github action for tagged issues

---

kubernetes/overlays/prod/base/hmi/hmi-server-deployment.yaml

Writes all log messages as JSON in staging and production environments

chore: enable jaon logging

---

kubernetes/overlays/prod/overlays/askem-staging/check-latest/images.txt

This adds the skema services to list of things that auto update when their docker image changes

chore: add skema services to list of auto updates for check-latest

---

README.md

Adding instructions to install ansible for secrets to work.
Resolves #984

chore: add ansible install instructions

---

kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml
kubernetes/overlays/prod/overlays/askem-staging/check-latest/images.txt
kubernetes/overlays/prod/overlays/askem-staging/kustomization.yaml

Simulation Service name update. Trying to save Daniel a few seconds for this change
-> Did not re-deploy as you know

chore: from scheduler to service name change

---

kubernetes/overlays/prod/base/kustomization.yaml
kubernetes/overlays/prod/base/services/simulation-service-deployment.yaml

Add minimal set of environment variables for simulation service. 
https://github.com/DARPA-ASKEM/simulation-service/blob/main/src/Settings.jl#L58#L64

chore: env vars for simulation-service

---

kubernetes/base/services/hmi-extraction-service/hmi-extraction-service-deployment.yaml
kubernetes/base/services/hmi-extraction-service/hmi-extraction-service.yaml
kubernetes/base/services/hmi-extraction-service/kustomization.yaml
kubernetes/overlays/dev/local/services/hmi-extraction-service/hmi-extraction-service.yaml
kubernetes/overlays/dev/local/services/hmi-extraction-service/kustomization.yaml
kubernetes/overlays/prod/base/services/hmi-extraction-service/hmi-extraction-service-deployment.yaml
kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml
kubernetes/overlays/prod/overlays/askem-staging/ingress/private-web-ingress.yaml
kubernetes/overlays/prod/overlays/askem-staging/kustomization.yaml
kubernetes/overlays/prod/overlays/askem-staging/services/hmi-extraction-service/hmi-extraction-service.yaml

Added the new `hmi-extraction-service` .  I think it's all here.

feat: added hmi extraction service to orchestration

---

kubernetes/overlays/prod/base/services/simulation-service/simulation-service-deployment.yaml

Update env-var as per changes in simulation-service
https://github.com/DARPA-ASKEM/simulation-service/commit/d41d2ebc89a4b64d099c4c58e9da9556fc5fc938

chore: update env var

---

kubernetes/overlays/prod/base/services/simulation-service/simulation-service-deployment.yaml

Trying to resolve in simulation-service deployment startup
```
ERROR: LoadError: ArgumentError: invalid Bool representation: "\"false\""
Stacktrace:
[1] tryparse_internal(#unused#::Type{Bool}, sbuff::String, startpos::Int64, endpos::Int64, base::Int64, raise::Bool)
```

fix: change "false" back to false

---

kubernetes/overlays/prod/base/services/simulation-service/simulation-service-deployment.yaml

fix: redo false string

---

kubernetes/dev_deploy.sh
kubernetes/functions.sh
kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml
kubernetes/production_deploy.sh

chore: added deployment scripts checks and updated tags

---

kubernetes/base/hmi/documentation/kustomization.yaml
kubernetes/base/hmi/documentation/terarium-docs-deployment.yaml
kubernetes/base/hmi/documentation/terarium-docs-service.yaml
kubernetes/overlays/dev/local/hmi/documentation/kustomization.yaml
kubernetes/overlays/dev/local/hmi/documentation/terarium-docs-service.yaml
kubernetes/overlays/prod/base/hmi/documentation/terarium-docs-deployment.yaml
kubernetes/overlays/prod/base/kustomization.yaml
kubernetes/overlays/prod/overlays/askem-staging/hmi/documentation/terarium-docs-service.yaml
kubernetes/overlays/prod/overlays/askem-staging/ingress/private-web-ingress.yaml
kubernetes/overlays/prod/overlays/askem-staging/kustomization.yaml

chore: added documentation to dev and staging deployments

---

kubernetes/base/services/data-service/data-service-deployment.yaml
kubernetes/overlays/dev/local/services/data-service/data-service-deployment.yaml
kubernetes/overlays/dev/local/services/data-service/kustomization.yaml
kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml
kubernetes/overlays/prod/overlays/askem-staging/kustomization.yaml

chore: add migration container

---

kubernetes/overlays/dev/local/gateway/envoy/config.yaml

fix: local deployment

---

kubernetes/overlays/dev/local/gateway/envoy/config.yaml.template

fix: typo fix

---

kubernetes/overlays/dev/local/gateway/configmap/host-linux.yaml

fix: fixed linux template

---

kubernetes/overlays/dev/local/gateway/gateway-httpd-deployment.yaml

fix: local funman

---

kubernetes/overlays/dev/local/services/pyciemss-service/pyciemss-api-deployment.yaml
kubernetes/overlays/dev/local/services/pyciemss-service/pyciemss-worker-deployment.yaml
kubernetes/overlays/prod/base/services/pyciemss-service/pyciemss-worker-deployment.yaml

fix: pyciemss tds url

---

kubernetes/overlays/dev/local/services/funman/kustomization.yaml
kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml
kubernetes/overlays/prod/overlays/askem-staging/kustomization.yaml

update funman image

---

kubernetes/overlays/prod/base/hmi/server/hmi-server-deployment.yaml

Pyciemss api var

---

kubernetes/overlays/prod/overlays/askem-staging/services/jupyter-llm/jupyter-llm-deployment.yaml

add jupyter to unique node in staging

---

kubernetes/overlays/prod/overlays/askem-staging/kustomization.yaml
kubernetes/overlays/prod/overlays/askem-staging/services/skema/skema-tr-deployment.yaml

add skema-tr to its own node

---

kubernetes/overlays/prod/base/services/simulation-service/simulation-service-deployment.yaml

fix: update simulation service url environment

---

kubernetes/overlays/prod/base/hmi/server/hmi-server-deployment.yaml

fix: use hosted version of mit unified in staging and prod

---

kubernetes/overlays/prod/base/hmi/server/hmi-server-deployment.yaml

use extraction-service-api

---

kubernetes/base/hmi/server/hmi-server-deployment.yaml

specify upload max file size

---

kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml
kubernetes/overlays/prod/overlays/askem-staging/check-latest/images.txt

feat: update tags for latest in prod

---

kubernetes/base/services/simulation-service/simulation-service-deployment.yaml

Up to two in production environments

feat: up the replicas on simulation service

---

kubernetes/overlays/dev/local/services/funman/kustomization.yaml
kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml
kubernetes/overlays/prod/overlays/askem-staging/kustomization.yaml

update funman to 1.6.0

---

kubernetes/overlays/prod/base/services/data-service/data-service-deployment.yaml

Artifact bucket should be set for staging (And prod)

---

kubernetes/overlays/dev/local/hmi/server/hmi-server-deployment.yaml

Removing colon from here, as it causes a double colon in terarium.
Note: this PR requires https://github.com/DARPA-ASKEM/Terarium/pull/1682 to be ✅ before merging

Removing breaking colon from port

---

kubernetes/overlays/prod/overlays/askem-staging/kustomization.yaml
kubernetes/overlays/prod/overlays/askem-staging/services/mit/mit-tr-service.yaml

task: let `mit-tr` open to the world

---

kubernetes/overlays/prod/base/services/ta1-service/ta1-service-worker-deployment.yaml

* update `ta1-service` to use local MIT services `http://mit-tr:4046` instead of MIT self-hosted `http://3.83.68.208`.

task: update ta1-service-worker-deployment.yaml

---

kubernetes/dev_deploy.sh

Update available services in dev_deploy.sh

chore: update available services

---

kubernetes/overlays/dev/local/hmi/documentation/kustomization.yaml
kubernetes/overlays/prod/base/services/knowledge-middleware/knowledge-middleware-api-deployment.yaml
kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml
kubernetes/overlays/prod/overlays/askem-staging/kustomization.yaml

update docs image to latest

---

kubernetes/overlays/prod/overlays/askem-staging/ingress/private-web-ingress.yaml

Adding message-queue UI to staging's ingress
Please give this a sanity check

Adding MQ 15672 to ingress

---

kubernetes/overlays/prod/overlays/askem-production/services/sciml-service/sciml-service-deployment.yaml
kubernetes/overlays/prod/overlays/askem-staging/services/sciml-service/sciml-service-deployment.yaml

Update connection setup for MQ
Depends on:  https://github.com/DARPA-ASKEM/sciml-service/pull/131

ampqs config for sciml services

---

kubernetes/base/services/sciml-service/sciml-service-deployment.yaml

initial config

---

kubernetes/overlays/prod/overlays/askem-production/services/sciml-service/sciml-service-deployment.yaml
kubernetes/overlays/prod/overlays/askem-staging/services/sciml-service/sciml-service-deployment.yaml

- I believe this service keeps toppling every node it runs on, I'm hoping limiting the resources will stop exhausting every node. Feel free to let me know if these resources are not enough for service, I'm basing this off grafana data. We have 4vCPU x 16GB RAM for each (5) node.

feat: add resource constraints to sciml service

---

kubernetes/overlays/prod/overlays/askem-production/hmi/server/hmi-server-deployment.yaml
kubernetes/overlays/prod/overlays/askem-staging/hmi/server/hmi-server-deployment.yaml

Staging and production need correct queue names
Resolves #2183

[fix: hmi-server] Working on AMPQ to handle multiple hmi-server instance

---

kubernetes/overlays/prod/overlays/askem-staging/ingress/private-web-ingress.yaml

This fixes the vulnerability where things go public randomly.. 

bug: fix security group to close external access

---

kubernetes/base/services/skema/skema-rs-deployment.yaml

new env vars

---

kubernetes/overlays/prod/overlays/askem-production/check-latest/images.txt
kubernetes/overlays/prod/overlays/askem-staging/check-latest/images.txt

Check latest fails to update images due to the funman manifest returning a 404

funman manifest fails to be pulled

---

architecture/system-arch.py
kubernetes/overlays/prod/base/hmi/server/hmi-server-deployment.yaml

added missing vars

---

kubernetes/base/services/funman/funman-deployment.yaml
kubernetes/overlays/prod/overlays/askem-staging/services/funman/funman-deployment.yaml

remove FUNMAN_BASE_URL

---

kubernetes/base/services/gollm/gollm-deployment.yaml
kubernetes/base/services/gollm/gollm-service.yaml
kubernetes/base/services/gollm/kustomization.yaml
kubernetes/overlays/prod/base/kustomization.yaml
kubernetes/overlays/prod/base/services/gollm/gollm-deployment.yaml
kubernetes/overlays/prod/base/services/gollm/gollm-service.yaml
kubernetes/overlays/prod/overlays/askem-production/check-latest/images.txt
kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml
kubernetes/overlays/prod/overlays/askem-production/services/gollm/gollm-deployment.yaml
kubernetes/overlays/prod/overlays/askem-staging/check-latest/images.txt
kubernetes/overlays/prod/overlays/askem-staging/kustomization.yaml
kubernetes/overlays/prod/overlays/askem-staging/services/gollm/gollm-deployment.yaml

initial GoLLM deployment

---

kubernetes/overlays/prod/overlays/askem-staging/ingress/private-web-ingress.yaml

expose gollm to vpn

---

kubernetes/base/services/beaker/beaker-deployment.yaml
kubernetes/overlays/prod/base/services/knowledge-middleware/knowledge-middleware-api-deployment.yaml
kubernetes/overlays/prod/base/services/knowledge-middleware/knowledge-middleware-worker-deployment.yaml
kubernetes/overlays/prod/base/services/pyciemss-service/pyciemss-api-deployment.yaml
kubernetes/overlays/prod/base/services/pyciemss-service/pyciemss-worker-deployment.yaml

* Correcting URL for dataservice to HMI
* Adding Credentials for KM and pyciemss

[fix: services] Fix services for hmi

---

kubernetes/base/services/beaker/beaker-deployment.yaml
kubernetes/overlays/prod/base/services/knowledge-middleware/knowledge-middleware-api-deployment.yaml
kubernetes/overlays/prod/base/services/knowledge-middleware/knowledge-middleware-worker-deployment.yaml
kubernetes/overlays/prod/base/services/pyciemss-service/pyciemss-api-deployment.yaml
kubernetes/overlays/prod/base/services/pyciemss-service/pyciemss-worker-deployment.yaml
kubernetes/overlays/prod/base/services/sciml-service/sciml-service-deployment.yaml

342 add basicauth credentials

---

kubernetes/overlays/prod/overlays/askem-staging/kustomization.yaml

Change packages to use `tds-migration` instead of `latest`.

Use tds-migration images

---

kubernetes/overlays/prod/overlays/askem-staging/hmi/server/hmi-server-deployment.yaml

Reverts DARPA-ASKEM/orchestration#355

Revert "increase log level to DEBUG on staging"

---

kubernetes/overlays/prod/overlays/askem-production/check-latest/images.txt
kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml

Reverts DARPA-ASKEM/orchestration#356

Revert "Choose a different hmi-server"

---

kubernetes/overlays/prod/overlays/askem-production/hmi/server/hmi-server-deployment.yaml
kubernetes/overlays/prod/overlays/askem-staging/hmi/server/hmi-server-deployment.yaml

* Remove unneeded suffixes
Resolves #2666

[fix: rabbitmq] Fix complex queues

---

kubernetes/overlays/prod/overlays/askem-production/services/beaker/beaker-deployment.yaml
kubernetes/overlays/prod/overlays/askem-staging/services/beaker/beaker-deployment.yaml

- Updating the tolerations for beaker, please redeploy when you guys get a chance so its rescheduled on the node with more resources (easier to setup a new node than to mess with the auto scaling groups)

#10024 updated tolerations for beaker

---

kubernetes/overlays/prod/overlays/askem-staging/ingress/private-web-ingress.yaml

- This SG keeps flipping staging to public 😬...

remove k8s sg group

---

kubernetes/base/hmi/server/hmi-server-service.yaml
kubernetes/base/services/mit/mit-proxy-deployment.yaml
kubernetes/overlays/prod/base/services/beaker/beaker-persistent-volume.yaml
kubernetes/overlays/prod/base/services/beaker/beaker-pv-claim.yaml
kubernetes/overlays/prod/base/services/climate-data/climate-data-deployment.yaml

fix MIT_BASE_URL and ESGF_URL

---

kubernetes/overlays/prod/base/hmi/server/hmi-server-deployment.yaml
kubernetes/overlays/prod/overlays/askem-production/hmi/server/hmi-server-deployment.yaml

use local mit and skema-unified

---

kubernetes/overlays/prod/overlays/askem-staging/hmi/server/hmi-server-deployment.yaml

to help `yarn dev` usuage

---

kubernetes/base/services/skema/skema-unified-deployment.yaml

add the missing R

---

kubernetes/overlays/prod/overlays/askem-production/services/beaker/beaker-deployment.yaml

add limits to beaker

---

kubernetes/base/services/mit/mit-tr-deployment.yaml

add openai_api_key env var

---

kubernetes/overlays/prod/base/services/pyciemss-service/pyciemss-api-deployment.yaml
kubernetes/overlays/prod/base/services/pyciemss-service/pyciemss-worker-deployment.yaml
kubernetes/overlays/prod/base/services/sciml-service/sciml-service-deployment.yaml
kubernetes/overlays/prod/overlays/askem-production/secrets/secrets-mq-creds.enc.yaml
kubernetes/overlays/prod/overlays/askem-production/services/pyciemss-service/pyciemss-api-deployment.yaml
kubernetes/overlays/prod/overlays/askem-production/services/pyciemss-service/pyciemss-worker-deployment.yaml
kubernetes/overlays/prod/overlays/askem-production/services/sciml-service/sciml-service-deployment.yaml
kubernetes/overlays/prod/overlays/askem-staging/secrets/secrets-mq-creds.enc.yaml
kubernetes/overlays/prod/overlays/askem-staging/services/pyciemss-service/pyciemss-api-deployment.yaml
kubernetes/overlays/prod/overlays/askem-staging/services/pyciemss-service/pyciemss-worker-deployment.yaml
kubernetes/overlays/prod/overlays/askem-staging/services/sciml-service/sciml-service-deployment.yaml

move staging to new rabbit MQ.

---

kubernetes/overlays/prod/base/services/beaker/beaker-deployment.yaml

add new env vars

---

kubernetes/overlays/prod/overlays/askem-staging/ingress/private-web-ingress.yaml

-  This sg group makes the private ingress public, unsure what happened here but I fixed this a while ago 🤷

fix sg group to private

---

kubernetes/overlays/prod/overlays/askem-dev/keycloak/keycloak-deployment.yaml
kubernetes/overlays/prod/overlays/askem-production/keycloak/keycloak-deployment.yaml

remove keycloak from staging

---

kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml
orctl/src/models/secret_files.rs

update prod to 2.14.1 (and better secret file descriptions for orctl)

---

kubernetes/base/services/cosmos/cosmos-deployment.yaml
kubernetes/overlays/prod/base/hmi/server/hmi-server-deployment.yaml
kubernetes/overlays/prod/base/kustomization.yaml

Increase connection pool

---

kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml

update to 2.14.4

---

kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml

update to 2.15.0

---

kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml

update pycienss to 1.13.0

---

kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml

candidate release for july 31 demo

bump version to 2.17.0

---

kubernetes/overlays/prod/base/services/beaker/beaker-deployment.yaml

Just testing with this in my .env in beaker and running locally

updating mira_rest_url in beaker

---

kubernetes/base/services/skema/skema-unified-deployment.yaml
kubernetes/overlays/prod/overlays/askem-dev/ingress/private-web-ingress.yaml
kubernetes/overlays/prod/overlays/askem-dev/kustomization.yaml
kubernetes/overlays/prod/overlays/askem-staging/ingress/private-web-ingress.yaml

Resolves DARPA-ASKEM/terarium#3688

remove all mention of skema-text-reading

---

kubernetes/overlays/prod/base/hmi/server/hmi-server-deployment.yaml
kubernetes/overlays/prod/overlays/askem-dev/secrets/secrets-adobe-api-key.enc.yaml
kubernetes/overlays/prod/overlays/askem-production/secrets/secrets-adobe-api-key.enc.yaml
kubernetes/overlays/prod/overlays/askem-staging/secrets/secrets-adobe-api-key.enc.yaml

deployed - to dev and staging (and will be deployed to prod when someone redeploys prod)

Adobe localhost key to environments

---

kubernetes/overlays/prod/base/services/beaker/beaker-deployment.yaml

update mira endpoint
