DARPA-ASKEM/orchestration

- README.md
- kubernetes/local/deploy-terarium.sh
- kubernetes/local/gateway-keycloak-deployment.yaml
Upon trying to start the orchestration, I noticed some issue with starting the keycloack pod, and the proposed changes are meant to remove those issues.
Also, a "dev" option is added to start the TERArium deployment without starting the hmi client / server, which often will be launched locally by the developer!
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
> chore: fix orchestration issue related to starting the keycloack pod

- CONTRIBUTING.md
- README.md
- kubernetes/local/deploy-terarium.sh
* Remembering how to stop a service is not really clear, and the documentation is not fully made.
* I added to more commands `dev:hmi-client` and `dev:hmi-server` to start all the TERArium services except the one named.
* I cleaned up the script:
* use the long flags form 
* simplify the long list of files by using `*` 
* added comments
* added `kubectl rollout status` to wait for keycloak to start before the `hmi-server`
* Run the commands `dev:no-hmi-client` should start all services except `hmi-client`
* Run the commands `dev:no-hmi-server` should start all services except `hmi-server`
> feat: update deploy-terarium.sh

- kubernetes/local/gateway-postgres-deployment.yaml
This uses a docker image of Postgres stored in the GitHub docker repository. This ensures that if the image is not present on the host machine, the local k8s cluster is able to pull the image without having to create more tokens and add separate secrets.
The stack is able to start and run with the new image tag.
> fix: use a docker image of postgres on ghcr.io so k8s is able to pull it

- README.md
Fixing the link to the lint badge as the underlying CI file has been renamed
> docs: fix link to the badge after ci refactoring

- kubernetes/local/document-service-deployment.yaml
Add `ghcr-cred` to the `document-service` deployment script.
> fix: add credentials for document service

- kubernetes/local/deploy-terarium.sh
We do not need this command, it is confusing at best.
Developer should start the whole cluster, then stop the ones they want to run locally one by one.
> chore: remove the `dev` startup command

- kubernetes/base/services/skema/kustomization.yaml
- kubernetes/base/services/skema/skema-memgraph-deployment.yaml
- kubernetes/base/services/skema/skema-memgraph-service.yaml
- kubernetes/base/services/skema/skema-py-deployment.yaml
- kubernetes/base/services/skema/skema-py-service.yaml
- kubernetes/base/services/skema/skema-rs-deployment.yaml
- kubernetes/base/services/skema/skema-rs-service.yaml
- kubernetes/overlays/prod/base/hmi/hmi-server-deployment.yaml
- kubernetes/overlays/prod/base/kustomization.yaml
- kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml
- kubernetes/overlays/prod/overlays/askem-staging/kustomization.yaml
- kubernetes/overlays/prod/overlays/askem-staging/services/skema-py-ingress.yaml
- kubernetes/overlays/prod/overlays/askem-staging/services/skema-rs-ingress.yaml
This adds the skema components to the staging and production kubernetes cluster.  This is currently deploy and configured on staging. We add an ingress so that local development can use this service without needing to run the components locally.  
The main components (in docker-compose form):
```yaml
services:
skema-py:
image: skema-py:latest
ports:
- "8008:8000"
command: ["uvicorn", "server:app", "--host", "0.0.0.0"]
skema-rs:
image: skema-rs:latest
entrypoint: cargo run --release --bin skema_service -- --host 0.0.0.0 --db-host database
ports:
- "8080:8080"
database:
image: "memgraph/memgraph-platform"
ports:
- "7687:7687"
- "3000:3000"
- "7444:7444"
entrypoint: ["/usr/bin/supervisord"]
```
These three services have been configured in `base` but only added to the customize for the `prod` …
> chore: add skema to staging and prod kube cluster

- kubernetes/overlays/prod/base/hmi/hmi-server-deployment.yaml
Ensure we provide the url for the model service in the base hmi-deployment manifest.
This fix is already deployed to `staging.terarium.ai` but needs to be applied to production.
> fix: fix model-service being unreachable in staging and production

- kubernetes/overlays/prod/overlays/askem-staging/gateway/gateway-httpd-deployment.yaml
- kubernetes/overlays/prod/overlays/askem-staging/hmi/hmi-server-deployment.yaml
- kubernetes/overlays/prod/overlays/askem-staging/kustomization.yaml
- kubernetes/production_deploy.sh
`hmi-server` LASTEST needs environment variable `realm` set
Caveats: currently set to `Uncharted` as staging is still using that realm
Running the deployment puts gateway-admin-keycloak into the deployed stack, however, it is not ready for prime time - manually removing it (in case one deploys to staging (or production))
> feat: add missing realm details needed for hmi-latest

- kubernetes/base/services/model-service/model-service-service.yaml
- kubernetes/overlays/prod/overlays/askem-staging/services/model-service-ingress.yaml
This was missing from a previous PR that moved model-service into staging for local deployment.  This ensures the service runs as a `NodePort` and also that it has an ingress available to configure DNS
> chore: add an ingress for model service and ensure it runs as a node port

- README.md
Specialized ansible install version for arm64 processors
can't use x86 version
Resolves #noissue
> chore: updating docs for ARM64 processors

- kubernetes/dev_deploy.sh
- kubernetes/overlays/dev/local/secrets/kustomization.yaml
Allow individual services to be deployed, as opposed to bring everything up and selectively taking down services. This should avoid the initial memory surge needed to bring up the entire dev tech stack.
> feat: script to do optional local deployment

- kubernetes/base/services/extraction-service/kustomization.yaml
- kubernetes/base/services/ta1-service/kustomization.yaml
- kubernetes/base/services/ta1-service/ta1-service-api-deployment.yaml
- kubernetes/base/services/ta1-service/ta1-service-api.yaml
- kubernetes/base/services/ta1-service/ta1-service-worker-deployment.yaml
Renaming of deployment code for `extraction-service` to `ta1-service`. 
Note that this is done on the builds on the `ta1-service` repo so this _ought to_ work but I'm no expert in this deployment setup.
> rename extraction service/worker to ta1 service

- kubernetes/overlays/dev/local/hmi/server/hmi-server-deployment.yaml
- kubernetes/overlays/prod/base/hmi/server/hmi-server-deployment.yaml
* Removing AWS secrets from hmi-server's deployment as its no longer needed. 
* Fixing reserved character combo `::` in terarium's `application.properties`
Note this PR must be merged around the same time as https://github.com/DARPA-ASKEM/Terarium/pull/1716
Resolves #1704
> 1704 task clean dependencies 1

- kubernetes/overlays/dev/local/gateway/configmap/host-mac.yaml
- kubernetes/overlays/prod/base/services/simulation-service/simulation-service-deployment.yaml
> Fix simulation-service env var names

- kubernetes/overlays/prod/overlays/askem-staging/kustomization.yaml
- kubernetes/overlays/prod/overlays/askem-staging/services/skema/skema-tr-service.yaml
Changes the skema tr service to be a nodeport for ingress to work properly
> bug: fix skema tr service to be nodeport

- kubernetes/overlays/prod/overlays/askem-production/check-latest/images.txt
- kubernetes/overlays/prod/overlays/askem-production/kustomization.yaml
Use a version of hmi-server that was created before the tds-migration merge.
> Choose a different hmi-server

- kubernetes/overlays/prod/base/hmi/server/hmi-server-deployment.yaml
flyway is disabled by default to avoid accidental updates from devs in an upcoming PR
> Enable Flyway on staging and production

- kubernetes/overlays/prod/overlays/askem-staging/check-latest/check-latest-cronjob.yaml
schedule of `"*/5 * * * 1-3,5-7"` = every 5 mins (or mins/5 when remainder is zero), all hours, all days of the month, all months, 1-3 (monday-wednesday), 5-7 (friday-sunday)
could also represent the days of the week as `1,2,3,5,6,7` but I like the minus sign more :)
Useful tool: https://crontab.guru/#*/5_*_*_*_1-3,5-7
> Check Latest not run on Thrusdays on Staging

- kubernetes/overlays/prod/overlays/askem-dev/ingress/private-web-ingress.yaml
- kubernetes/overlays/prod/overlays/askem-dev/ingress/private-web-ssl-ingress.yaml
- I believe this will resolve the 502s we're seeing
Resolves:
```
2024/06/05 18:40:43 [error] 6198#6198: *20870713 upstream sent too big header while reading response header from upstream, client: 10.64.18.187, server: keycloak.dev.terarium.ai, request: "GET /realms/terarium/protocol/openid-connect/auth?client_id=app&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F%3FconfigHash%3D17975ac7&response_type=code&scope=openid+profile&state=af511483dab9438f8beff8aa04475dbf&code_challenge=U58qWvfW-Z_liFrueCQNpIO5OLQ5zNZMumXpiZoSHUE&code_challenge_method=S256&response_mode=query HTTP/1.0", upstream: "https://10.244.4.112:8443/realms/terarium/protocol/openid-connect/auth?client_id=app&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F%3FconfigHash%3D17975ac7&response_type=code&scope=openid+profile&state=af5 …
```
> fix nginx proxy buffer size

- kubernetes/base/services/cosmos/cosmos-deployment.yaml
HTTP Checks are only valid for 200..<400 and therefore 404s fail.  TCP checks pass if the server responds at all
> Fix Cosmos Health Check

- kubernetes/overlays/prod/overlays/askem-dev/services/beaker/beaker-service.yaml
- kubernetes/overlays/prod/overlays/askem-dev/services/climate-data/climate-data-service.yaml
- kubernetes/overlays/prod/overlays/askem-dev/services/cosmos/cosmos-service.yaml
- kubernetes/overlays/prod/overlays/askem-dev/services/data-service/data-service-graphdb-service.yaml
- kubernetes/overlays/prod/overlays/askem-dev/services/mit/mit-tr-service.yaml
- kubernetes/overlays/prod/overlays/askem-dev/services/pyciemss-service/pyciemss-api-service.yaml
- kubernetes/overlays/prod/overlays/askem-dev/services/redis/redis-service.yaml
- kubernetes/overlays/prod/overlays/askem-dev/services/sciml-service/sciml-service-service.yaml
- kubernetes/overlays/prod/overlays/askem-dev/services/skema/skema-rs-service.yaml
- kubernetes/overlays/prod/overlays/askem-dev/services/skema/skema-text-reading-service.yaml
- kubernetes/overlays/prod/overlays/askem-dev/services/skema/skema-unified-service.yaml
- I moved these ClusterIPs while debugging the websocket stuff, moving these back to nodeports so we can access from our internal frontend.
> move these services back to nodeports
